# Site settings
title: Stefano Marzorati
email: stefano@marzorati.co
description: "ICT System Administrator"
baseurl: "/blog"
url: "http://stefano.marzorati.co/blog"
twitter_username: marzorati_ste
github_username:  marste
facebook_username:  stefano.marzorati

# Build settings
markdown: kramdown
permalink: pretty
paginate: 0
exclude: ["node_modules"]
